### ISSUE TITLE
Bug: Fix broken image link in contracts architecture diagram

### ISSUE THREAD

**Issue by aleon1220** [aws-samples/aws-serverless-developer-experience-workshop-java#35]
### Expected Behaviour

Developing Unicorn Contracts
documentation broken link 

I expect to see the image with the contract architecture
![image](https://github.com/aws-samples/aws-serverless-developer-experience-workshop-java/assets/2084646/b86cb6b1-1668-4267-b7fb-26df267c027d)

### Current Behaviour

The S3 link is supposed to be public but is showing not accessible 
Link is https://static.us-east-1.prod.workshops.aws/public/fd291886-89c4-4336-b21b-5747484b495d/static/images/architecture-contracts.png

### Code snippet

This link from a workshop works Fine but i guess it will work only during the workshop availability.

I uploaded the image anyway ![image](https://github.com/aws-samples/aws-serverless-developer-experience-workshop-java/assets/2084646/b86cb6b1-1668-4267-b7fb-26df267c027d) 

```csharp
https://static.us-east-1.prod.workshops.aws/0d80f594-9f86-499a-96af-7df1001b90f9/static/images/architecture-contracts.png?Key-Pair-Id=K36Q2WVO3JP7QD&Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cHM6Ly9zdGF0aWMudXMtZWFzdC0xLnByb2Qud29ya3Nob3BzLmF3cy8wZDgwZjU5NC05Zjg2LTQ5OWEtOTZhZi03ZGYxMDAxYjkwZjkvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTU4OTU1N319fV19&Signature=a0YXSjLThiQHtx7iN3OwgKIc%7EdP2tsg847S06eltuHMYiOhpopDVFSW5bWY0W8oQkflV9QfTVYip5BDVUrR55Eo6T-LxTsGcYSVw7ZjLYZS8ANno4I-WWvoDhgGgBSjC4ABkxD4ooc4riJkzM1AT3ukE37vPMVKRbxE7gRhcRlhrhqqnIoHmK%7EdE91tgcg7u2Pj6kUqupjB1zNyoN5ZI7n3JDD0DI-XKk%7EuUFvzfHb%7EIqfsUV6RyA02NPgojkVtdWOb5-icwQp6C0w-
```

### Possible Solution

update S3 permissions for the image object. It is also impacting the main README for this project.

### Steps to Reproduce

Access the links

**Comment by sliedig** [comment]
This is now fixed, thank you!
